#!/usr/bin/env bash
# Prepare the ach-agent testbed: verify the ach-memory stack, write ./.env.
#
# There is nothing to mint any more. ach-memory issues no credentials: identity is
# delegated, and on the compose stack `deploy/dev-identity/whoami.py` echoes the bearer
# token back as the user id. So the token IS the identity — pick a name, send it, and you
# are that person with that person's bank. Two names are two people.
#
# Nothing here provisions anything either: `retain` creates and provisions a project on
# first write, and every read tool reports an absent project as empty rather than as an
# error. A cold start is the contract, not a setup step — check_memory.py tests exactly it.
set -euo pipefail

cd "$(dirname "$0")"

MEMORY_URL="${MEMORY_URL:-http://127.0.0.1:8000}"
MEMORY_NETWORK="${MEMORY_NETWORK:-ach-memory_default}"
# Whatever name you want the agent to be. Not a secret; it is passed as a Bearer token
# only because that is the header the platform resolver reads.
MEMORY_IDENTITY="${MEMORY_IDENTITY:-testbed-agent}"
WAIT_SECONDS="${WAIT_SECONDS:-60}"

die() { echo "ERROR: $*" >&2; exit 1; }

# --- the stack is up ---------------------------------------------------------------------
# Bounded: WAIT_SECONDS ceiling, then a failure path. A naked `until curl; do sleep; done`
# would hang forever when the stack is simply not running.
deadline=$((SECONDS + WAIT_SECONDS))
until curl -fsS -o /dev/null "$MEMORY_URL/health" 2>/dev/null; do
  if (( SECONDS >= deadline )); then
    die "ach-memory did not answer $MEMORY_URL/health within ${WAIT_SECONDS}s. See README.md
for the compose command that brings it up with the Host allowlist this testbed needs."
  fi
  sleep 2
done

# --- the DNS-rebinding allowlist ---------------------------------------------------------
# The MCP transport matches the Host header INCLUDING the port. The harness reaches the
# service in-network as `api:8000`, and the shipped default only covers loopback, so
# without that exact string every MCP call comes back 421 — long after /health looked fine.
api_container=$(docker ps --filter "name=api" --filter "network=$MEMORY_NETWORK" --format '{{.Names}}' | head -1)
if [[ -n "$api_container" ]]; then
  allowed=$(docker inspect "$api_container" \
    --format '{{range .Config.Env}}{{println .}}{{end}}' | sed -n 's/^MEMORY_MCP_ALLOWED_HOSTS=//p')
  case "$allowed" in
    *api:8000*) ;;
    *) die "the ach-memory api allows Hosts [$allowed] — 'api:8000' is missing, so every MCP
call from the harness will fail 421. Restart the memory stack with the command in README.md." ;;
  esac
else
  echo "WARN: no api container found on network '$MEMORY_NETWORK' — skipping the Host-allowlist check." >&2
fi

docker network inspect "$MEMORY_NETWORK" >/dev/null 2>&1 \
  || die "docker network '$MEMORY_NETWORK' not found. Bring the memory stack up first, or set MEMORY_NETWORK."

# --- hand it to compose ------------------------------------------------------------------
# ./.env is read automatically by `docker compose` in this directory, and is gitignored.
# The var keeps its ACH_SECRET_ name because that is the contract with the harness: it is
# read from the environment at use time and stripped from anything opencode inherits.
umask 077
cat > .env <<EOF
# Generated by bootstrap.sh. Not committed (.gitignore).
ACH_SECRET_MEMORY_ACHMEMORY=$MEMORY_IDENTITY
MEMORY_NETWORK=$MEMORY_NETWORK
EOF

echo "identity '$MEMORY_IDENTITY' written to docker/testbed/.env"
echo "next: uv run python check_memory.py    (or: ACH_TOKEN=ek-... docker compose run --rm agent)"
